import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import Navbar from "@/components/nav";
import ThemeContextProvider from "@/providers/theme-provider";
import { Suspense } from "react";
import Location from "@/components/location";
import { ToastProvider } from "@/providers/toast-provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
 
  return (
    <SessionProvider session={session}>
      <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>
          <Location />
          <ThemeContextProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Suspense fallback={<div>Loading......................</div>}>
              <Navbar />
            </Suspense>
            {children}
          </ThemeContextProvider>
          <ToastProvider />
        </body>
      </html>
    </SessionProvider>
  );
}
