import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignIn, UserButton } from "@clerk/nextjs";
import Navbar from "@/components/nav";
import ThemeContextProvider from "@/providers/theme-provider";
import { Suspense } from "react";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>
        <ThemeContextProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Suspense fallback={<div>Loading......................</div>}>
          <Navbar />

            </Suspense>
          {children}
          </ThemeContextProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
